version: 2.1
 # we now have TWO jobs, so that a workflow can coordinate them!
 jobs:
   # This is our first job.
   one:
     # it uses the docker executor
     docker:
       # specifically, a docker image with ruby 2.4.1
       - image: circleci/ruby:2.4.1
     # Steps are a list of commands to run inside the docker container above.
     steps:
       # this pulls pulls code down from GitHub
       - checkout
       # This prints "A first hello" to stdout.
       - run: echo "A first hello"
       # a command telling the job to "sleep" for 25 seconds.
       - run: sleep 25
   # This is our second job.
   two:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A more familiar hi" 
       - run: sleep 15 
 # Under the workflows: map, we can coordinate our two jobs, defined above.
 workflows:
   version: 2
   one_and_two: # this is the name of our workflow
     jobs: # and here we list the jobs we are going to run.
       - one
       - two
